services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: estate_ai
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  maildev:
    image: maildev/maildev:latest
    restart: unless-stopped
    ports:
      - "1080:1080" #web UI
      - "1025:1025" # SMTP
volumes:
  db_data:
